- name: Prompt for user input
  ansible.builtin.pause:
    prompt: "{{ user_var_name }}"
    echo: yes
  register: user_input_result
  when: (user_var_name is defined) and (vars[user_var_name] | default('') | length == 0)

- name: Set input as fact
  ansible.builtin.set_fact:
    "{{ user_var_name }}": "{{ user_input_result.user_input }}"
  when: user_input_result is not skipped
