---
# defaults/main.yml
git_base_url: https://raw.githubusercontent.com
git_username: your-username
git_repo: your-repo
yml_file_path: path/to/yourfile.yml
git_version_1: branch1
git_version_2: branch2
_git_repo_url: "{{ git_base_url }}/{{ git_username }}/{{ git_repo }}"
file_uri_version_1: "{{ _git_repo_url }}/{{ git_version_1 }}/{{ yml_file_path }}"
file_uri_version_2: "{{ _git_repo_url }}/{{ git_version_2 }}/{{ yml_file_path }}"
managed_secrets_dirname: managed_secrets
managed_secrets_path: "{{ (ansible_env.HOME, managed_secrets_dirname) | path_join }}"
managed_secret_name: github_personal_access_token
github_personal_access_token: "{{ lookup('file', managed_secrets_path+'/'+managed_secret_name) }}"
