# roles/apply_defaults_to_awx_configuration/tasks/main.yml

- name: Apply defaults to AWX configuration
  set_fact:
    awx_configuration: "{{ awx_configuration | combine(defaults, recursive=True) }}"
  loop: "{{ awx_configuration.organizations | default({}) | dict2items }}"
  vars:
    defaults: "{{ awx_configuration._defaults | default({}) }}"
  loop_control:
    loop_var: org_item
  when: org_item.key != '_defaults'

- name: Remove _defaults from AWX configuration
  set_fact:
    awx_configuration: "{{ awx_configuration | combine(omit, recursive=True) }}"
  loop: "{{ awx_configuration.organizations | default({}) | dict2items }}"
  loop_control:
    loop_var: org_item
  when: org_item.key == '_defaults'
