---
- name: Ensure vars repo exists locally
  include_role:
    name: managed_git_repos
    tasks_from: single_repo.yml
    public: true
  
- name: Load vars from managed ansible vars repo path
  include_role:
    name: load_vars_from_path
  vars:
    load_vars_path: "{{ managed_git_repo_path }}"